export const LoginPic = {
  logo: require(`../static/image/logo@2x.png`),
  loginBtn: require('../static/image/bg_btn@2x.png'),
  wxBtn: require('../static/image/pic_wechat_h@2x.png'),
  agreeBtn: require('../static/image/btn_sellect_h@2x.png'),
};

export const iconPic = {
  cart_gray:require('../static/image/ico_cart_gray@2x.png'),
  like_gray:require('../static/image/ico_like_gray@2x.png'),
  service_gray:require('../static/image/ico_service_gray@2x.png'),
  more: require('../static/image/ico_more_h@2x.png'),
  blue_more:require('../static/image/blue_more.png'),
  blue_down_arrow:require('../static/image/blue_down_arrow.png'),
  backBlack: require('../static/image/back-black.png'),
  back_with_bk:require('../static/image/back-with-bk.png'),
  search: require('../static/image/nav_ico_search_h@2x.png'),
  vip: require('../static/image/ico-vip.png'),
  share: require('../static/image/share.png'),
  share_back_black:require('../static/image/nav_ico_back_h.png'),
  close: require('../static/image/close.png'),
  triangle: require('../static/image/ico_point_d@2x.png'),
  _close: require('../static/image/nav_ico_back_h@2x.png'),
  wx: require('../static/image/icon_wechat_h@2x.png'),
  wx_react: require('../static/image/icon_wechat_h_react@2x.png'),
  zfb_react: require('../static/image/pic_alipay_reat@2x.png'),
  btn_success: require('../static/image/btn_succeed_h@2x.png'),
  edit: require('../static/image/ico_edit_h@2x.png'),
  add_head:require('../static/image/ico_add_h@2x.png'),
  active_love:require('../static/image/ico_thumbsup_n copy@2x.png'),
  camera:require('../static/image/btn_upload_h@2x.png'),
  star:require('../static/image/ico_like_n@2x.png'),
  info:require('../static/image/ico_comment_n@2x.png'),
  give_link:require('../static/image/ico_like_n.png'),
  rod:require('../static/image/ico_like_b.png'),
  write:require('../static/image/ico_share_h.png'),
  dot:require('../static/image/ico_point_d.png'),
  my_answer:require('../static/image/btn_answer_h.png'),
  Ask_quize:require('../static/image/btn_quize_h.png'),
  alarm_clock:require('../static/image/ico_history__d.png'),
  up:require('../static/image/ico_start_h.png'),
  end:require('../static/image/ico_start_h copy.png'),
  receiving:require('../static/image/ico_notice_h@2x.png'),
  car:require('../static/image/ico_logistics_h@2x.png'),
  message:require('../static/image/ico_news_h@2x.png'),
  right:require('../static/image/btn_more_right@2x.png'),
  round_arrow:require('../static/image/nav_ico_share_h.png'),
  bottom:require('../static/image/btn_more_bottom.png'),
  red_envelope:require('../static/image/ico_vip_red.png'),
  default_link:require('../static/image/ico_thumbsup_n.png'),
  pen:require('../static/image/btn_answer_h@2x.png'),
  play_v:require('../static/image/btn_play_v.png'),
};
